//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weixin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bg_Mains
    {
        public int id { get; set; }
        public Nullable<int> organize_id { get; set; }
        public Nullable<int> horganize_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> hdept_id { get; set; }
        public Nullable<int> platform_id { get; set; }
        public Nullable<int> bus_id { get; set; }
        public string ef_flag { get; set; }
        public Nullable<int> declare_id { get; set; }
        public string entry_type { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> hstatus_id { get; set; }
        public Nullable<int> hcustomer_id { get; set; }
        public string hcustomer_no { get; set; }
        public string hcustomer_name { get; set; }
        public string hcust_linkman { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string customer_no { get; set; }
        public string customer_name { get; set; }
        public string cust_linkman { get; set; }
        public string records_no { get; set; }
        public string goods_name { get; set; }
        public Nullable<System.DateTime> indate_dt { get; set; }
        public Nullable<System.DateTime> apply_dt { get; set; }
        public string apply_no { get; set; }
        public string custom_apply_no { get; set; }
        public string unify_no { get; set; }
        public string verify_no { get; set; }
        public string barcode_no { get; set; }
        public string transmode_no { get; set; }
        public string factory_no { get; set; }
        public string factory_name { get; set; }
        public string shipper_no { get; set; }
        public string shipper_name { get; set; }
        public string consignee_no { get; set; }
        public string consignee_name { get; set; }
        public string agent_no { get; set; }
        public string agent_name { get; set; }
        public string transname { get; set; }
        public string cabin_no { get; set; }
        public string serial_no { get; set; }
        public string trade_no { get; set; }
        public string drawback_no { get; set; }
        public string imposemode_no { get; set; }
        public string remitmode_no { get; set; }
        public Nullable<decimal> imposepro { get; set; }
        public string licence_no { get; set; }
        public string start_country_no { get; set; }
        public string loadport_no { get; set; }
        public string end_country_no { get; set; }
        public string bargainmode_no { get; set; }
        public string freightmode_no { get; set; }
        public string freight_currency_no { get; set; }
        public Nullable<System.DateTime> loadport_dt { get; set; }
        public Nullable<decimal> freight { get; set; }
        public string subscribemode_no { get; set; }
        public string subscribe_currency_no { get; set; }
        public Nullable<decimal> subscribe { get; set; }
        public string incidentalmode_no { get; set; }
        public string incidental_currency_no { get; set; }
        public Nullable<decimal> incidental { get; set; }
        public string contract_no { get; set; }
        public Nullable<int> piece { get; set; }
        public string pack_no { get; set; }
        public Nullable<decimal> grossweight { get; set; }
        public Nullable<decimal> netweight { get; set; }
        public string truck_no { get; set; }
        public Nullable<int> declare_group_id { get; set; }
        public Nullable<System.DateTime> receive_dt { get; set; }
        public Nullable<int> receive_id { get; set; }
        public Nullable<System.DateTime> tally_dt { get; set; }
        public Nullable<int> tally_id { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
        public Nullable<byte> pass_yn { get; set; }
        public Nullable<System.DateTime> pass_dt { get; set; }
        public Nullable<System.DateTime> inspect_pass_dt { get; set; }
        public Nullable<byte> complete_yn { get; set; }
        public Nullable<int> complete_id { get; set; }
        public Nullable<System.DateTime> complete_dt { get; set; }
        public string bus_no { get; set; }
        public string accompany_no { get; set; }
        public string check_no { get; set; }
        public string vessel { get; set; }
        public string voyage { get; set; }
        public string zcd_cbbh { get; set; }
        public string zcd_lxr { get; set; }
        public string zcd_lxdh { get; set; }
        public string book_no { get; set; }
        public string wharf_name { get; set; }
        public string ship_agent_no { get; set; }
        public string ship_agent_name { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> drawback_dt { get; set; }
        public string factory { get; set; }
        public string entrust_no { get; set; }
        public Nullable<int> container_count { get; set; }
        public Nullable<int> num_20 { get; set; }
        public Nullable<int> num_40 { get; set; }
        public string mark { get; set; }
        public Nullable<int> edi_yn { get; set; }
        public Nullable<int> nobook_yn { get; set; }
        public Nullable<int> back_yn { get; set; }
        public Nullable<int> change_yn { get; set; }
        public Nullable<int> trans { get; set; }
        public Nullable<int> reprints { get; set; }
        public string container_no1 { get; set; }
        public Nullable<int> zx_yn { get; set; }
        public string port_no { get; set; }
        public Nullable<int> import_cabin_id { get; set; }
        public Nullable<System.DateTime> import_cabin_dt { get; set; }
        public Nullable<int> logical_check_id { get; set; }
        public Nullable<System.DateTime> logical_check_dt { get; set; }
        public Nullable<int> audit_by { get; set; }
        public Nullable<System.DateTime> audit_dt { get; set; }
        public string zgd_customer_name { get; set; }
        public Nullable<System.DateTime> swipe_dt { get; set; }
        public Nullable<int> swipe_by { get; set; }
        public string qpstatus { get; set; }
        public string tgdstatus { get; set; }
        public string cost_note { get; set; }
        public string charge_note { get; set; }
        public Nullable<int> num_goods { get; set; }
        public Nullable<decimal> zzs_cost { get; set; }
        public Nullable<decimal> gs_cost { get; set; }
        public Nullable<decimal> xfs_cost { get; set; }
        public Nullable<decimal> qts_cost { get; set; }
        public Nullable<int> hgcg_count { get; set; }
        public Nullable<int> hgcg_20 { get; set; }
        public Nullable<int> hgcg_40 { get; set; }
        public Nullable<decimal> hgcg_cost { get; set; }
        public Nullable<int> hgcg_by { get; set; }
        public Nullable<System.DateTime> hgcg_dt { get; set; }
        public Nullable<int> sjcg_count { get; set; }
        public Nullable<int> sjcg_20 { get; set; }
        public Nullable<int> sjcg_40 { get; set; }
        public Nullable<decimal> sjcg_cost { get; set; }
        public Nullable<int> sjcg_by { get; set; }
        public Nullable<System.DateTime> sjcg_dt { get; set; }
        public Nullable<System.DateTime> contract_dt { get; set; }
        public Nullable<System.DateTime> invoice_dt { get; set; }
        public string invoice_no { get; set; }
        public string seller_address { get; set; }
        public string seller_tel { get; set; }
        public string buyers_address { get; set; }
        public string buyers_tel { get; set; }
        public string signed_at { get; set; }
        public string vessel2 { get; set; }
        public string voyage2 { get; set; }
        public string boxis { get; set; }
        public string jkkxtype { get; set; }
    }
}
