//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weixin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes
    {
        public int id { get; set; }
        public Nullable<int> zclass_id { get; set; }
        public string zucode { get; set; }
        public string znamec { get; set; }
        public Nullable<int> zsequence { get; set; }
        public string ztype { get; set; }
        public string znamee { get; set; }
        public string zucode_p { get; set; }
    }
}
