//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weixin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public int id { get; set; }
        public string zucode { get; set; }
        public string ste_no { get; set; }
        public string znamec { get; set; }
        public Nullable<System.DateTime> limit_dt { get; set; }
        public Nullable<System.DateTime> exp_dt { get; set; }
        public string com_type { get; set; }
        public string com_Level { get; set; }
        public string ientry_type { get; set; }
        public string oentry_type { get; set; }
        public Nullable<int> zx_yn { get; set; }
        public string seal_pic { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
    }
}
