//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weixin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterData
    {
        public int id { get; set; }
        public string way { get; set; }
        public string upper { get; set; }
        public string lower { get; set; }
        public string handler { get; set; }
        public Nullable<System.DateTime> create_dt { get; set; }
        public string contents { get; set; }
    }
}
