//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weixin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stcodes
    {
        public int id { get; set; }
        public Nullable<int> ver_ts { get; set; }
        public string code_ts { get; set; }
        public string g_name { get; set; }
        public string control { get; set; }
        public string unit_no { get; set; }
        public string sunit_no { get; set; }
        public string low_rate { get; set; }
        public string high_rate { get; set; }
        public string tax_type { get; set; }
        public string tax_rate { get; set; }
        public string note_s { get; set; }
        public string BEGIN_DATE { get; set; }
        public string END_DATE { get; set; }
        public string LSJM_FLAG { get; set; }
        public string TARIFF_MARK { get; set; }
        public string DUTY_TYPE { get; set; }
        public string COM_V_LOW_RATE { get; set; }
        public string COM_V_HIGH_RATE { get; set; }
        public string COM_Q_LOW_RATE { get; set; }
        public string COM_Q_HIGH_RATE { get; set; }
        public string COM_UNIT_FLAG { get; set; }
        public string COM_LOW_CTL_PRICE { get; set; }
        public string COM_HIGH_CTL_PRICE { get; set; }
        public string COM_CTL_CURR { get; set; }
        public string OUT_RATE { get; set; }
        public string REG_TYPE { get; set; }
        public string REG_RATE { get; set; }
        public string REG_Q_LOW_RATE { get; set; }
        public string REG_Q_HIGH_RATE { get; set; }
        public string REG_UNIT_FLAG { get; set; }
        public string REG_CTL_PRICE { get; set; }
        public string REG_CTL_CURR { get; set; }
        public string TAIWAN_RATE { get; set; }
        public string OTHER_TYPE { get; set; }
        public string OTHER_RATE { get; set; }
        public string ILOW_PRICE { get; set; }
        public string IHIGH_PRICE { get; set; }
        public string ELOW_PRICE { get; set; }
        public string EHIGH_PRICE { get; set; }
        public string MAX_IN { get; set; }
        public string MAX_OUT { get; set; }
        public string CHK_PRICE { get; set; }
        public string OUT_DUTY_TYPE { get; set; }
        public string OUT_COM_UNIT_FLAG { get; set; }
        public string OUT_COM_Q_RATE { get; set; }
    }
}
