//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weixin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users
    {
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Pwd { get; set; }
        public string Sex { get; set; }
        public string Remark { get; set; }
        public string VerifyCode { get; set; }
        public string IsValid { get; set; }
        public string openId_ibaoguan { get; set; }
        public string openId_ebaoguan { get; set; }
    }
}
