//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Weixin.Models
{
    [DataContract(IsReference = true)]
    public partial class We_Message: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int message_id
        {
            get { return _message_id; }
            set
            {
                if (_message_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“message_id”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _message_id = value;
                    OnPropertyChanged("message_id");
                }
            }
        }
        private int _message_id;
    
        [DataMember]
        public string fromUser
        {
            get { return _fromUser; }
            set
            {
                if (_fromUser != value)
                {
                    _fromUser = value;
                    OnPropertyChanged("fromUser");
                }
            }
        }
        private string _fromUser;
    
        [DataMember]
        public string toUser
        {
            get { return _toUser; }
            set
            {
                if (_toUser != value)
                {
                    _toUser = value;
                    OnPropertyChanged("toUser");
                }
            }
        }
        private string _toUser;
    
        [DataMember]
        public Nullable<System.DateTime> create_time
        {
            get { return _create_time; }
            set
            {
                if (_create_time != value)
                {
                    _create_time = value;
                    OnPropertyChanged("create_time");
                }
            }
        }
        private Nullable<System.DateTime> _create_time;
    
        [DataMember]
        public string origin
        {
            get { return _origin; }
            set
            {
                if (_origin != value)
                {
                    _origin = value;
                    OnPropertyChanged("origin");
                }
            }
        }
        private string _origin;
    
        [DataMember]
        public string msgtype
        {
            get { return _msgtype; }
            set
            {
                if (_msgtype != value)
                {
                    _msgtype = value;
                    OnPropertyChanged("msgtype");
                }
            }
        }
        private string _msgtype;
    
        [DataMember]
        public string @event
        {
            get { return _event; }
            set
            {
                if (_event != value)
                {
                    _event = value;
                    OnPropertyChanged("event");
                }
            }
        }
        private string _event;
    
        [DataMember]
        public string msgContent
        {
            get { return _msgContent; }
            set
            {
                if (_msgContent != value)
                {
                    _msgContent = value;
                    OnPropertyChanged("msgContent");
                }
            }
        }
        private string _msgContent;
    
        [DataMember]
        public string status
        {
            get { return _status; }
            set
            {
                if (_status != value)
                {
                    _status = value;
                    OnPropertyChanged("status");
                }
            }
        }
        private string _status;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion
    }
}
